=== fredfred2/arquitectura/webservices/solutions/lab03/Practice3-3/cardschema.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
           xmlns="urn:dukesdecks"
           elementFormDefault="qualified"
           targetNamespace="urn:dukesdecks"
           jaxb:version="2.1">

    <xs:simpleType name="suitType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CLUBS" />
            <xs:enumeration value="DIAMONDS" />
            <xs:enumeration value="HEARTS" />
            <xs:enumeration value="SPADES" />
        </xs:restriction>
    </xs:simpleType>
   
    <xs:simpleType name="colorType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="RED" />
            <xs:enumeration value="BLACK" />
        </xs:restriction>
    </xs:simpleType>
   
    <xs:simpleType name="rankType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="2">
                <xs:annotation>
                    <xs:appinfo>
                        <jaxb:typesafeEnumMember name="TWO"/>
                    </xs:appinfo>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="3">
                <xs:annotation>
                    <xs:appinfo>
                        <jaxb:typesafeEnumMember name="THREE"/>
                    </xs:appinfo>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="4">
                <xs:annotation>
                    <xs:appinfo>
                        <jaxb:typesafeEnumMember name="FOUR"/>
                    </xs:appinfo>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="5">
                <xs:annotation>
                    <xs:appinfo>
                        <jaxb:typesafeEnumMember name="FIVE"/>
                    </xs:appinfo>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="6">
                <xs:annotation>
                    <xs:appinfo>
                        <jaxb:typesafeEnumMember name="SIX"/>
                    </xs:appinfo>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="7">
                <xs:annotation>
                    <xs:appinfo>
                        <jaxb:typesafeEnumMember name="SEVEN"/>
                    </xs:appinfo>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="8">
                <xs:annotation>
                    <xs:appinfo>
                        <jaxb:typesafeEnumMember name="EIGHT"/>
                    </xs:appinfo>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="9">
                <xs:annotation>
                    <xs:appinfo>
                        <jaxb:typesafeEnumMember name="NINE"/>
                    </xs:appinfo>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="10">
                <xs:annotation>
                    <xs:appinfo>
                        <jaxb:typesafeEnumMember name="TEN"/>
                    </xs:appinfo>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="J">
                <xs:annotation>
                    <xs:appinfo>
                        <jaxb:typesafeEnumMember name="JACK"/>
                    </xs:appinfo>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="Q">
                <xs:annotation>
                    <xs:appinfo>
                        <jaxb:typesafeEnumMember name="QUEEN"/>
                    </xs:appinfo>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="K">
                <xs:annotation>
                    <xs:appinfo>
                        <jaxb:typesafeEnumMember name="KING"/>
                    </xs:appinfo>
                </xs:annotation>
            </xs:enumeration>            
            <xs:enumeration value="A">
                <xs:annotation>
                    <xs:appinfo>
                        <jaxb:typesafeEnumMember name="ACE"/>
                    </xs:appinfo>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="JOKER">
                <xs:annotation>
                    <xs:appinfo>
                        <jaxb:typesafeEnumMember name="JOKER"/>
                    </xs:appinfo>
                </xs:annotation>
            </xs:enumeration>
            <!--
            <xs:enumeration value="2" />
            <xs:enumeration value="3" />
            <xs:enumeration value="4" />
            <xs:enumeration value="5" />
            <xs:enumeration value="6" />
            <xs:enumeration value="7" />
            <xs:enumeration value="8" />
            <xs:enumeration value="9" />
            <xs:enumeration value="10" />
            <xs:enumeration value="J" />
            <xs:enumeration value="Q" />
            <xs:enumeration value="K" />
            <xs:enumeration value="A" />
            <xs:enumeration value="JOKER" />
            -->
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="cardType">
        <xs:complexContent>
            <xs:restriction base="xs:anyType">
                <xs:sequence>
                    <xs:element name="rank" type="rankType" />
                    <xs:choice>
                        <xs:element name="suit" type="suitType" />
                        <xs:element name="color" type="colorType" />
                    </xs:choice>
                </xs:sequence>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="stackType">
        <xs:sequence>
            <xs:element name="card" type="cardType" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:appinfo>
                        <jaxb:property name="cards"/>
                    </xs:appinfo>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="stack" type="stackType" />
    
</xs:schema>

=== fredfred2/arquitectura/webservices/solutions/lab03/Practice3-2/JavaToSchema/src/cardstack.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<stack xmlns="urn:dukesdecks" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="cardschema.xsd">
    <card>
        <rank>7</rank>
        <suit>HEARTS</suit>
    </card>
    <card>
        <rank>J</rank>
        <suit>CLUBS</suit>
    </card>
    <card>
        <rank>9</rank>
        <suit>DIAMONDS</suit>
    </card>
    <card>
        <rank>5</rank>
        <suit>CLUBS</suit>
    </card>
    <card>
        <rank>K</rank>
        <suit>SPADES</suit>
    </card>
    <card>
        <rank>4</rank>
        <suit>HEARTS</suit>
    </card>
    <card>
        <rank>A</rank>
        <suit>DIAMONDS</suit>
    </card>
    <card>
        <rank>K</rank>
        <suit>HEARTS</suit>
    </card>
    <card>
        <rank>6</rank>
        <suit>SPADES</suit>
    </card>
    <card>
        <rank>6</rank>
        <suit>CLUBS</suit>
    </card>
    <card>
        <rank>5</rank>
        <suit>HEARTS</suit>
    </card>
    <card>
        <rank>7</rank>
        <suit>DIAMONDS</suit>
    </card>
    <card>
        <rank>Q</rank>
        <suit>SPADES</suit>
    </card>
    <card>
        <rank>2</rank>
        <suit>CLUBS</suit>
    </card>
    <card>
        <rank>7</rank>
        <suit>CLUBS</suit>
    </card>
    <card>
        <rank>J</rank>
        <suit>SPADES</suit>
    </card>
    <card>
        <rank>Q</rank>
        <suit>HEARTS</suit>
    </card>
    <card>
        <rank>2</rank>
        <suit>SPADES</suit>
    </card>
    <card>
        <rank>8</rank>
        <suit>DIAMONDS</suit>
    </card>
    <card>
        <rank>10</rank>
        <suit>HEARTS</suit>
    </card>
    <card>
        <rank>10</rank>
        <suit>DIAMONDS</suit>
    </card>
    <card>
        <rank>3</rank>
        <suit>DIAMONDS</suit>
    </card>
    <card>
        <rank>5</rank>
        <suit>SPADES</suit>
    </card>
    <card>
        <rank>10</rank>
        <suit>SPADES</suit>
    </card>
    <card>
        <rank>J</rank>
        <suit>DIAMONDS</suit>
    </card>
    <card>
        <rank>9</rank>
        <suit>SPADES</suit>
    </card>
    <card>
        <rank>8</rank>
        <suit>HEARTS</suit>
    </card>
    <card>
        <rank>K</rank>
        <suit>DIAMONDS</suit>
    </card>
    <card>
        <rank>2</rank>
        <suit>DIAMONDS</suit>
    </card>
    <card>
        <rank>A</rank>
        <suit>HEARTS</suit>
    </card>
    <card>
        <rank>9</rank>
        <suit>CLUBS</suit>
    </card>
    <card>
        <rank>4</rank>
        <suit>DIAMONDS</suit>
    </card>
    <card>
        <rank>10</rank>
        <suit>CLUBS</suit>
    </card>
    <card>
        <rank>5</rank>
        <suit>DIAMONDS</suit>
    </card>
    <card>
        <rank>3</rank>
        <suit>CLUBS</suit>
    </card>
    <card>
        <rank>7</rank>
        <suit>SPADES</suit>
    </card>
    <card>
        <rank>K</rank>
        <suit>CLUBS</suit>
    </card>
    <card>
        <rank>3</rank>
        <suit>HEARTS</suit>
    </card>
    <card>
        <rank>8</rank>
        <suit>CLUBS</suit>
    </card>
    <card>
        <rank>4</rank>
        <suit>SPADES</suit>
    </card>
    <card>
        <rank>3</rank>
        <suit>SPADES</suit>
    </card>
    <card>
        <rank>Q</rank>
        <suit>DIAMONDS</suit>
    </card>
    <card>
        <rank>6</rank>
        <suit>HEARTS</suit>
    </card>
    <card>
        <rank>4</rank>
        <suit>CLUBS</suit>
    </card>
    <card>
        <rank>6</rank>
        <suit>DIAMONDS</suit>
    </card>
    <card>
        <rank>A</rank>
        <suit>CLUBS</suit>
    </card>
    <card>
        <rank>2</rank>
        <suit>HEARTS</suit>
    </card>
    <card>
        <rank>A</rank>
        <suit>SPADES</suit>
    </card>
    <card>
        <rank>J</rank>
        <suit>HEARTS</suit>
    </card>
    <card>
        <rank>Q</rank>
        <suit>CLUBS</suit>
    </card>
    <card>
        <rank>8</rank>
        <suit>SPADES</suit>
    </card>
    <card>
        <rank>9</rank>
        <suit>HEARTS</suit>
    </card>
</stack>

=== fredfred2/arquitectura/webservices/solutions/lab03/Practice3-1/SchemaToJava/src/cardstack.xml
<?xml version="1.0" encoding="UTF-8"?>

<dd:stack xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:dd="urn:dukesdecks"
       xsi:schemaLocation="urn:dukesdecks cardschema.xsd">
    <dd:card>
        <dd:rank>4</dd:rank>
        <dd:suit>SPADES</dd:suit>
    </dd:card>
    <dd:card>
        <dd:rank>2</dd:rank>
        <dd:suit>CLUBS</dd:suit>
    </dd:card>
    <dd:card>
        <dd:rank>JOKER</dd:rank>
        <dd:color>RED</dd:color>
    </dd:card>
</dd:stack>
